version: '3.4'

services:
  postmantoswagger:
    image: postmantoswagger:first
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
